#!/usr/bin/env bash
# Create .env with fresh random passwords and the matching Mosquitto password
# file. Idempotent: an existing .env is left alone unless --force is given,
# because rotating passwords silently would break Home Assistant's stored MQTT
# config entry and every flashed device.
#
#   ./scripts/gen-secrets.sh            # create if missing
#   ./scripts/gen-secrets.sh --force    # regenerate everything (breaks clients)
set -euo pipefail

cd "$(dirname "$0")/.."
STACK_DIR="$PWD"
ENV_FILE="$STACK_DIR/.env"
PASSWD_FILE="$STACK_DIR/mosquitto/config/passwd"
MOSQ_IMAGE="eclipse-mosquitto:2.0.22"

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ -f "$ENV_FILE" ] && [ "$FORCE" -eq 0 ]; then
  echo "==> .env already exists, keeping it (use --force to regenerate)"
else
  echo "==> generating .env with random passwords"
  randpw() { tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 28; }
  umask 077
  cat > "$ENV_FILE" <<ENVEOF
# Generated by scripts/gen-secrets.sh on $(date -Iseconds)
# chmod 600, gitignored. Do not commit.

TZ=Europe/Moscow

HA_MQTT_USER=homeassistant
HA_MQTT_PASSWORD=$(randpw)

WEATHER_COLLECTOR_MQTT_USER=weather_collector
WEATHER_COLLECTOR_MQTT_PASSWORD=$(randpw)

RF_COLLECTOR_MQTT_USER=rf_collector
RF_COLLECTOR_MQTT_PASSWORD=$(randpw)

WATCH_MQTT_USER=watch
WATCH_MQTT_PASSWORD=$(randpw)

WEATHER_ENGINE_MQTT_USER=weather_engine
WEATHER_ENGINE_MQTT_PASSWORD=$(randpw)

MESHCORE_MQTT_USER=meshcore
MESHCORE_MQTT_PASSWORD=$(randpw)

RTL433_MQTT_USER=rtl433
RTL433_MQTT_PASSWORD=$(randpw)

MONITOR_MQTT_USER=monitor
MONITOR_MQTT_PASSWORD=$(randpw)

LAN_SUBNET=192.168.1.0/24
ENVEOF
  chmod 600 "$ENV_FILE"
fi

# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

echo "==> building Mosquitto password file"
# Runs as root inside the container so it can write into the bind-mounted dir,
# then hands the file to uid 1883 (mosquitto) with group read for sergey.
docker run --rm --user root \
  -v "$STACK_DIR/mosquitto/config:/work" \
  -e P_HA="$HA_MQTT_PASSWORD" \
  -e P_WC="$WEATHER_COLLECTOR_MQTT_PASSWORD" \
  -e P_RF="$RF_COLLECTOR_MQTT_PASSWORD" \
  -e P_WATCH="$WATCH_MQTT_PASSWORD" \
  -e P_WE="$WEATHER_ENGINE_MQTT_PASSWORD" \
  -e P_MC="$MESHCORE_MQTT_PASSWORD" \
  -e P_RTL="$RTL433_MQTT_PASSWORD" \
  -e P_MON="$MONITOR_MQTT_PASSWORD" \
  -e U_HA="$HA_MQTT_USER" -e U_WC="$WEATHER_COLLECTOR_MQTT_USER" \
  -e U_RF="$RF_COLLECTOR_MQTT_USER" -e U_WATCH="$WATCH_MQTT_USER" \
  -e U_WE="$WEATHER_ENGINE_MQTT_USER" -e U_MC="$MESHCORE_MQTT_USER" \
  -e U_RTL="$RTL433_MQTT_USER" -e U_MON="$MONITOR_MQTT_USER" \
  "$MOSQ_IMAGE" sh -c '
    set -e
    rm -f /work/passwd
    mosquitto_passwd -c -b /work/passwd "$U_HA"    "$P_HA"
    mosquitto_passwd    -b /work/passwd "$U_WC"    "$P_WC"
    mosquitto_passwd    -b /work/passwd "$U_RF"    "$P_RF"
    mosquitto_passwd    -b /work/passwd "$U_WATCH" "$P_WATCH"
    mosquitto_passwd    -b /work/passwd "$U_WE"    "$P_WE"
    mosquitto_passwd    -b /work/passwd "$U_MC"    "$P_MC"
    mosquitto_passwd    -b /work/passwd "$U_RTL"   "$P_RTL"
    mosquitto_passwd    -b /work/passwd "$U_MON"   "$P_MON"
    chown 1883:1000 /work/passwd
    chmod 0640      /work/passwd
  '

echo "==> $(grep -c : "$PASSWD_FILE" 2>/dev/null || echo '?') accounts in mosquitto/config/passwd"
echo "==> done. Reload a running broker with:  docker compose exec mosquitto kill -HUP 1"
